
version: 2

models:
  - name: stg_fresh_enrollments
    description: This table contains the information of new enrolled student
    columns: 
      - name: enrollment_id
        description: Primary key(Unique key for each row) in this table
        tests:
          - not_null
          - unique
      - name: first_name
        description: First Name of student
      - name: last_name
        description: Last name of student
      - name: age
        description: Age of student 
        tests:
          - values_between_range:
              min_value: 13
              max_value: 75
      - name: gender
        description: gender of student
        tests: 
          - accepted_values:
              values: ['Female', 'Male', 'Unknown']
      - name: contact_number
        description: Contact number or Mobile number of student
      - name: email
        description: Email id or email address of student
      - name: city
        description: City of student
      - name: state
        description: State or Province of student
      - name: since_listening_in_years
        description: How long has student been listening to Acharya Ji
      - name: channel_id
        description: From which platform/channel student is coming
      - name: donation
        description: Amount of donation
      - name: counsellor_id
        description: Name of the counsellor of student 
      - name: enrollment_date
        description: Date of enrollment when was student enrolled

  - name: stg_channels
    description: This table contains the information of channels/platforms from where students are comming to enroll into Geeta Community/Samagam
    columns: 
      - name: channel_id
        description: Primary key(Unique indentifier for each row) in this table
        tests: 
          - not_null
          - unique
      - name: channel_name
        description: Name of the channel/platform 
        tests:
          - accepted_values:
              values: ['facebook', 'instagram', 'youtube', 'invite', 'website']
      
  - name: stg_counsellors
    description: This table contains the information of counsellor those enrolled students
    columns: 
      - name: counsellor_id
        description: Primary key(unique identifier for each row) in this table
        tests: 
          - not_null
          - unique
      - name: counsellor_name
        description: Name of the counsellor
        


